### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by seli11** [NiklasGollenstede/stop-fingerprinting#8]
can you make the screen resolutin to change with a buton click? 
like, click buton on top right resolutin change random 1280 × 720
click again  change random 720 × 480
click again ect,,,
this is the best plugin with no resolutin leaks,
and can you make a plugin to spof disable AudioContext, look in this page https://audiofingerprint.openwpm.com/
thnx for you hard work

**Comment by NiklasGollenstede** [comment]
I have already implemented what you are asking for in an (unstable) beta version.
Unfortunately, Mozilla plans some [massive changes](https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/) to the way add-ons work in Firefox.
I won't release any new Features until that is sorted out and I know what I can work with.

**Comment by seli11** [comment]
Niklas how to instal beta version? i have downloaded the zip file and renamed to .xpi but its say is corrupt!!

**Comment by NiklasGollenstede** [comment]
If you are referring to version 0.1.1b1 on AMO, then that's a totally different one, it's only meant to help with #7, but doesn't add any functionality.

As for Firefox saying it is corrupt, that's probably a bug. After disabling the current version and initiating the download again in a different tab, it should work.

The version with the additional options is not even on AMO, it attempts to do a lot of things and has a lot of options, but it also doesn't work reliably yet. It definitely can't be used yet.

**Comment by seli11** [comment]
when you plan to release the next version with other options?

**Comment by NiklasGollenstede** [comment]
The things this add-on does/should do are very low level, and since they are security relevant, they need to be done properly too.

Mozilla has not yet defined what will be possible with add-ons 9 month from now.
I cant start working or even plan to work until they do that.

If you want to know more about the current situation, you should really read this and some of the comments below: https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/
